- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-tests
    - basic-check-spec
    image: quay.io/operator-framework/scorecard-tests:v1.22.0
    labels:
      suite: basic
      test: basic-check-spec-tests
